### ISSUE TITLE
Bug related to colourscales when selecting certain DVs

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/dash-dv-explorer#50]
Symptom: Map does not update when certain DVs are selected. Amongst them: TJan2.5, TJan1.0.

Networking tab: 500 error on certain `_dash-update-component` requests. No further information.

Server log:
```
ERROR:dash_app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/dash/dash.py", line 1032, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/usr/local/lib/python3.6/site-packages/dash/dash.py", line 967, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "dash_app.py", line 305, in update_ds
    name=""
  File "/usr/local/lib/python3.6/site-packages/plotly/graph_objs/_heatmap.py", line 2264, in __init__
    self["colorscale"] = _v
  File "/usr/local/lib/python3.6/site-packages/plotly/basedatatypes.py", line 3932, in __setitem__
    self._set_prop(prop, value)
  File "/usr/local/lib/python3.6/site-packages/plotly/basedatatypes.py", line 4250, in _set_prop
    raise err
  File "/usr/local/lib/python3.6/site-packages/plotly/basedatatypes.py", line 4245, in _set_prop
    val = validator.validate_coerce(val)
  File "/usr/local/lib/python3.6/site-packages/_plotly_utils/basevalidators.py", line 1629, in validate_coerce
    self.raise_invalid_val(v)
  File "/usr/local/lib/python3.6/site-packages/_plotly_utils/basevalidators.py", line 285, in raise_invalid_val
    valid_clr_desc=self.description(),
ValueError: 
    Invalid value of type 'builtins.list' received for the 'colorscale' property of heatmap
        Received value: [[nan, '#053061'], [nan, '#053061'], [nan, '#256baf'], [nan, '#256baf'], [nan, '#559ec9'], [nan, '#559ec9'], [nan, '#a7d0e4'], [nan, '#a7d0e4'], [nan, '#e2edf3'], [nan, '#e2edf3'], [nan, '#fae7dc'], [nan, '#fae7dc'], [nan, '#f7b799'], [nan, '#f7b799'], [nan, '#dd6f59'], [nan, '#dd6f59'], [nan, '#b6202f'], [nan, '#b6202f'], [nan, '#67001f'], [nan, '#67001f']]

    The 'colorscale' property is a colorscale and may be
    specified as:
      - A list of colors that will be spaced evenly to create the colorscale.
        Many predefined colorscale lists are included in the sequential, diverging,
        and cyclical modules in the plotly.colors package.
      - A list of 2-element lists where the first element is the
        normalized color level value (starting at 0 and ending at 1), 
        and the second item is a valid color string.
        (e.g. [[0, 'green'], [0.5, 'red'], [1.0, 'rgb(0, 0, 255)']])
      - One of the following named colorscales:
            ['aggrnyl', 'agsunset', 'algae', 'amp', 'armyrose', 'balance',
             'blackbody', 'bluered', 'blues', 'blugrn', 'bluyl', 'brbg',
             'brwnyl', 'bugn', 'bupu', 'burg', 'burgyl', 'cividis', 'curl',
             'darkmint', 'deep', 'delta', 'dense', 'earth', 'edge', 'electric',
             'emrld', 'fall', 'geyser', 'gnbu', 'gray', 'greens', 'greys',
             'haline', 'hot', 'hsv', 'ice', 'icefire', 'inferno', 'jet',
             'magenta', 'magma', 'matter', 'mint', 'mrybm', 'mygbm', 'oranges',
             'orrd', 'oryel', 'peach', 'phase', 'picnic', 'pinkyl', 'piyg',
             'plasma', 'plotly3', 'portland', 'prgn', 'pubu', 'pubugn', 'puor',
             'purd', 'purp', 'purples', 'purpor', 'rainbow', 'rdbu', 'rdgy',
             'rdpu', 'rdylbu', 'rdylgn', 'redor', 'reds', 'solar', 'spectral',
             'speed', 'sunset', 'sunsetdark', 'teal', 'tealgrn', 'tealrose',
             'tempo', 'temps', 'thermal', 'tropic', 'turbid', 'twilight',
             'viridis', 'ylgn', 'ylgnbu', 'ylorbr', 'ylorrd'].
        Appending '_r' to a named colorscale reverses it.

172.18.0.1 - - [02/Mar/2021 22:14:58] "POST /_dash-update-component HTTP/1.1" 500 -
INFO:werkzeug:172.18.0.1 - - [02/Mar/2021 22:14:58] "POST /_dash-update-component HTTP/1.1" 500 -
```

**Comment by rod-glover** [comment]
Some values (temp, deg C) can be negative. Logscale computation fails. Question in to Charles about preferred fix: offset or no logscale for such variables.
